config/routes.rb
Rails.application.routes.draw do
  root to: 'contacts#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :contacts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :number, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]

  def index
    @contacts = Contact.all
  end

  def new
    @contact = Contact.new
  end

  def show
  end

  def edit
  end

  def update
    if @contact.update(contact_params)
      redirect_to contacts_path, notice: "Contact successfully updated!"
    else
      render :edit
    end
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      redirect_to contacts_path, notice: "Contact successfully Added"
    else 
      render :new
    end
  end

  def destroy
    if @contact.destroy
      redirect_to contacts_path, notice: "Contact successfully destroyed"
    end
  end

  private

  def set_contact
    @contact = Contact.find(params[:id])
  end

  def contact_params
    params.require(:contact).permit(:name, :number, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for(contact) do |form| %>
  <div class="field form-group">
    <%= form.text_field :name, placeholder: "Name", class: "form-control" %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.text_field :number, placeholder: "Number", class: "form-control" %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.email_field :email, placeholder: "Email", class: "form-control" %>
  </div>
  <br><br>
  <div class="actions">
    <%= form.submit class: "btn btn-primary"%>
  </div>
  <br>

<%end%>

app/views/contacts/edit.html.erb
<h1>Edit Contacts</h1>

<%= render 'form', contact: @contact %>
<%= link_to 'Back', contacts_path, class: "btn btn-dark" %>

app/views/contacts/index.html.erb
<h1>List of Contacts</h1>

<%= link_to 'Add Contact', new_contact_path, class: "btn btn-secondary"  %>

  <br><br>
  <table class="table table-striped table-hover"> 
    
    <thead>
      <tr>
        <th><strong>Name</th>
        <th><strong>Contact Number</strong></th>
        <th><strong>Email</strong></th>
      </tr>
    </thead>
    <tbody>
        <% @contacts.each do |contact| %>
           <tr>
             <th> 
                 <%= link_to contact.name, contact_path(contact), class: "link" %>
             </th>
             <th> 
                 <%= link_to contact.number, contact_path(contact), class: "link" %>
             </th>
             <th> 
                 <%= link_to contact.email, contact_path(contact),class: "link"  %>
             </th>
           </tr>
        <%end%>
     </tbody>

  </table>

app/views/contacts/new.html.erb
<h1>Add Contacts</h1>

<%= render 'form', contact: @contact %>
<%= link_to 'Back', contacts_path, class: "btn btn-dark" %>

app/views/contacts/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @contact.name %></h1>
  <p class="lead">Contact Number: <%= @contact.number %></p>
  <p class="lead">Email Address: <%= @contact.email %></p>
  <hr class="my-4">
  <p class="lead">
       <%= link_to 'Cancel', contacts_path, class: "btn btn-secondary" %>
       <%= link_to 'Edit', edit_contact_path, class: "btn btn-primary" %>
       <%= link_to 'Delete', contact_path, method: :delete, data: {confirm: "Are you sure? "}, class: "btn btn-danger" %>

  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Phonebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
    <p id="notice"><%= notice %></p>

    <div class = "container">
        <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>
</html>